name: "Dynamic Pipeline Example"
description: "An example pipeline that dynamically generates steps using a shell script."
emoji: ":twisted_rightwards_arrows:"
languages:
  - "Shell"
steps:
  - label: ":pipeline:"
    command: ".buildkite/pipeline.sh | buildkite-agent pipeline upload"